/*
 * Nombres de selección en español.
 *
 * El proveedor los manda en inglés —«Brazil», «Netherlands», «Ivory Coast»— y en
 * la quiniela se leen en español. Es una tabla de datos, sin lógica.
 *
 * Vivía COPIADA en importar_partidos.js y en jornadas.js: dos literales de unas
 * 230 líneas cada uno, con claves repetidas dentro de cada uno. Se compararon al
 * unificarlos en la Fase D y resultaron idénticos —147 entradas útiles, cero
 * discrepancias—, pura duplicación. Aquí está una sola vez y ordenada.
 *
 * Se expone como global, igual que `html` en html-seguro.js: las pantallas no
 * usan módulos.
 */
(function () {
  'use strict';

  const TRADUCCIONES = {
    "Afghanistan": "Afganistán",
    "Albania": "Albania",
    "Algeria": "Argelia",
    "Angola": "Angola",
    "Argentina": "Argentina",
    "Armenia": "Armenia",
    "Aruba": "Aruba",
    "Australia": "Australia",
    "Austria": "Austria",
    "Azerbaijan": "Azerbaiyán",
    "Bahrain": "Baréin",
    "Bangladesh": "Bangladés",
    "Belarus": "Bielorrusia",
    "Belgium": "Bélgica",
    "Belize": "Belice",
    "Benin": "Benín",
    "Bolivia": "Bolivia",
    "Bosnia and Herzegovina": "Bosnia y Herzegovina",
    "Botswana": "Botsuana",
    "Brazil": "Brasil",
    "Bulgaria": "Bulgaria",
    "Burkina Faso": "Burkina Faso",
    "Cameroon": "Camerún",
    "Canada": "Canadá",
    "Cape Verde": "Cabo Verde",
    "Chile": "Chile",
    "China": "China",
    "Chinese Taipei": "Taipéi Chino",
    "Colombia": "Colombia",
    "Costa Rica": "Costa Rica",
    "Croatia": "Croacia",
    "Cuba": "Cuba",
    "Curacao": "Curazao",
    "Czech Republic": "República Checa",
    "Denmark": "Dinamarca",
    "Dominican Republic": "República Dominicana",
    "Ecuador": "Ecuador",
    "Egypt": "Egipto",
    "El Salvador": "El Salvador",
    "England": "Inglaterra",
    "Estonia": "Estonia",
    "Fiji": "Fiyi",
    "Finland": "Finlandia",
    "France": "Francia",
    "Georgia": "Georgia",
    "Germany": "Alemania",
    "Ghana": "Ghana",
    "Guatemala": "Guatemala",
    "Guinea": "Guinea",
    "Guyana": "Guyana",
    "Haiti": "Haití",
    "Honduras": "Honduras",
    "Hong Kong": "Hong Kong",
    "Hungary": "Hungría",
    "Iceland": "Islandia",
    "India": "India",
    "Indonesia": "Indonesia",
    "Iran": "Irán",
    "Iraq": "Irak",
    "Ireland": "Irlanda",
    "Italy": "Italia",
    "Ivory Coast": "Costa de Marfil",
    "Jamaica": "Jamaica",
    "Japan": "Japón",
    "Jordan": "Jordania",
    "Kazakhstan": "Kazajistán",
    "Kenya": "Kenia",
    "Kosovo": "Kosovo",
    "Kuwait": "Kuwait",
    "Kyrgyzstan": "Kirguistán",
    "Latvia": "Letonia",
    "Lebanon": "Líbano",
    "Libya": "Libia",
    "Lithuania": "Lituania",
    "Luxembourg": "Luxemburgo",
    "Malaysia": "Malasia",
    "Mali": "Malí",
    "Mauritania": "Mauritania",
    "Mexico": "México",
    "Moldova": "Moldavia",
    "Mongolia": "Mongolia",
    "Montenegro": "Montenegro",
    "Morocco": "Marruecos",
    "Mozambique": "Mozambique",
    "Netherlands": "Países Bajos",
    "New Caledonia": "Nueva Caledonia",
    "New Zealand": "Nueva Zelanda",
    "Nicaragua": "Nicaragua",
    "Nigeria": "Nigeria",
    "North Korea": "Corea del Norte",
    "North Macedonia": "Macedonia del Norte",
    "Northern Ireland": "Irlanda del Norte",
    "Norway": "Noruega",
    "Oman": "Omán",
    "Pakistan": "Pakistán",
    "Palestine": "Palestina",
    "Panama": "Panamá",
    "Papua New Guinea": "Papúa Nueva Guinea",
    "Paraguay": "Paraguay",
    "Peru": "Perú",
    "Philippines": "Filipinas",
    "Poland": "Polonia",
    "Portugal": "Portugal",
    "Puerto Rico": "Puerto Rico",
    "Qatar": "Catar",
    "Romania": "Rumanía",
    "Samoa": "Samoa",
    "San Marino": "San Marino",
    "Saudi Arabia": "Arabia Saudita",
    "Scotland": "Escocia",
    "Senegal": "Senegal",
    "Serbia": "Serbia",
    "Singapore": "Singapur",
    "Slovakia": "Eslovaquia",
    "Slovenia": "Eslovenia",
    "Solomon Islands": "Islas Salomón",
    "South Africa": "Sudáfrica",
    "South Korea": "Corea del Sur",
    "Spain": "España",
    "Sudan": "Sudán",
    "Suriname": "Surinam",
    "Sweden": "Suecia",
    "Switzerland": "Suiza",
    "Syria": "Siria",
    "Tahiti": "Tahití",
    "Tajikistan": "Tayikistán",
    "Tanzania": "Tanzania",
    "Thailand": "Tailandia",
    "Togo": "Togo",
    "Trinidad & Tobago": "Trinidad y Tobago",
    "Tunisia": "Túnez",
    "Turkey": "Turquía",
    "Turkmenistan": "Turkmenistán",
    "Uganda": "Uganda",
    "Ukraine": "Ucrania",
    "United Arab Emirates": "Emiratos Árabes Unidos",
    "United States": "Estados Unidos",
    "Uruguay": "Uruguay",
    "USA": "Estados Unidos",
    "Uzbekistan": "Uzbekistán",
    "Vanuatu": "Vanuatu",
    "Venezuela": "Venezuela",
    "Vietnam": "Vietnam",
    "Wales": "Gales",
    "Yemen": "Yemen",
    "Zambia": "Zambia",
    "Zimbabwe": "Zimbabue"
  };

  /** El nombre en español si lo hay; si no, el original tal cual. */
  window.traducirEquipo = function traducirEquipo(nombre) {
    return TRADUCCIONES[nombre] || nombre;
  };
})();
